# Use the Miniconda image
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /usr/src/app

# Install git to clone the repository
RUN apt-get update && apt-get install -y git

# Clone the repository from GitHub into a specific directory
RUN git clone https://github.com/JeonSeongHu/discord-bot-test.git /usr/src/app/discord-bot

# Install the conda dependencies from conda_requirements.yaml
RUN conda env create -f /usr/src/app/discord-bot/conda_requirements.yaml

# Activate the conda environment
RUN echo "conda activate discord-bot" >> ~/.bashrc
ENV PATH /opt/conda/envs/discord-bot/bin:$PATH

# Set working directory to the cloned directory
WORKDIR /usr/src/app/discord-bot

# Run the bot
CMD ["python", "bot.py"]
